### ISSUE TITLE
Latest Documentation is empty

### ISSUE THREAD

**Issue by justuswilhelm** [JuliaDynamics/ConcurrentSim.jl#38]
This only shows the index page: https://benlauwens.github.io/SimJulia.jl/latest/index.html
The sidebar is unpopulated.
![screen shot 2017-09-09 at 17 46 13](https://user-images.githubusercontent.com/1641042/30238697-c9cc597e-9586-11e7-8bca-7af4eff543e5.png)

**Comment by BenLauwens** [comment]
Hi

I am aware of the lack of documentation. I am porting the [old documentation](http://simjuliajl.readthedocs.io/en/stable/welcome.html) to `Documenter` in the next weeks. So some patience and everything will be documented;) I keep this issue open till the documentation is completed.
Kind regards

Ben

**Comment by justuswilhelm** [comment]
Thanks a lot Ben, I really appreciate it and I am excited to start using SimJulia!

**Comment by ajkeith** [comment]
I took a swing at adding a basic M/M/c queue to the examples section of the documentation (PR #54). The Ross machine example was helpful, but a little complicated for me coming back to SimJulia after a while away. The tutorial was really helpful and basically includes an M/M/c queue but I thought it would be useful to have a separate self-contained M/M/c in the examples section.

**Comment by hboudali-rms** [comment]
Latest doc doesn't seem to cover everything!

**Comment by hdavid16** [comment]
Hi @BenLauwens any update on this? It has been over 3 years since this issue was opened...

**Comment by hdavid16** [comment]
It would be great to get this moving since not too much development on the package is being done currently. This could help others start using discrete event simulation in Julia!

**Comment by Krastanov** [comment]
The current documentation seems to cover the basics and since a day ago it is checked for correctness in CI. For the moment I will close this issue as the original problem is now fixed. However, if folks have suggestions for more fine-grained improvements, please speak up and file issues and pull requests! Improving the docs would certainly be great!
