### ISSUE TITLE
Add QSS solver to the common interface?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDynamics/ConcurrentSim.jl#52]
Hey, I was wondering if you could add bindings to the DifferentialEquations.jl common interface so that way the QSS solver could be benchmarked against the other ODE integrators. I am seeing nice claims but I haven't seen benchmarks against the other implementations so I am curious how well it performs in practice.

**Comment by BenLauwens** [comment]
Hi

One of my Phd students is reimplementing the QSS solver for Julia v0.7. The bindings to the common interface will be implemented once we have a stable product. I keep you informed.
Kind regards

Ben

**Comment by hdavid16** [comment]
Hi Ben, it seems like this issue is no longer relevant to SimJulia, should it be moved elsewhere?

**Comment by Krastanov** [comment]
@BenLauwens , I believe the QSS solver is not part of SimJulia anymore. I will close this issue, but please undo this if I am incorrect.
